In [2]:
import cv2
import numpy as np

In [3]:
img = np.ones((511,511,3)) #np will create a white frame
print(img)
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 ...

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Crating Black lines

In [4]:
#                    coordinates,   (B,G,R),(thickness)     B=blue,green,red
img = cv2.line(img,(0,0),(511,511),(0,0,0),5)
img = cv2.line(img,(511,0),(0,511),(0,0,0),5)
cv2.imshow("frame",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Creating Black lines

In [5]:
img = cv2.line(img,(0,0),(511,511),(0,0,0),5) # image, cordinates,colors,thickness
img = cv2.line(img,(0,511),(0,511),(0,0,),5)
cv2.imshow("Frame",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

##### Creating Blank frames

In [6]:
img = np.zeros((511,511,3))
print(img)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


##### Creating red lines

In [7]:
img = cv2.line(img,(0,0),(511,511),(0,0,255),5)
img = cv2.line(img,(0,511),(511,0),(0,0,255),6)
cv2.imshow("frame",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Creating rectangles

In [8]:
img_path =  "D:\\Code\Personal-Backup\\AIML\\OPENCV\\sample_images\\messi5.jpg"
img = cv2.imread(img_path,1)
img = cv2.rectangle(img,(150,50),(350,226),(0,0,255),2) # creating rectangele using two points
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()



##### Creating circles

In [9]:
img_path =  "D:\\Code\Personal-Backup\\AIML\\OPENCV\\sample_images\\messi5.jpg"
cv2.imread(img_path,1)
#                      center, radius,color,thickness
img = cv2.circle(img,(245,100),50,(0,255,255),5)
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


### Creating polygon

In [10]:
img = np.zeros([512,512,3])
pts = np.array([[200,200],[200,100],[400,100],[400,200],[300,250]],np.int32)
img = cv2.polylines(img,[pts],True,(0,255,255)) #true is parameter class close the polygon and false will remain open
cv2.imshow("frae",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
img_path =  "D:\\Code\Personal-Backup\\AIML\\OPENCV\\sample_images\\apple.jpg"
img = cv2.imread(img_path,1)
font = cv2.FONT_HERSHEY_COMPLEX    #ffont tye
            # string, coordinates
cv2.putText(img,'apple',(170,300),font,2,(255,255,0),3,cv2.LINE_AA)
cv2.imshow("FA",img)
cv2.waitKey(0)
cv2.destroyAllWindows()