### Numpy simple library


In [40]:
simple_list = [12,34,21,54,68,98,23,65]
print(simple_list,type(simple_list))

[12, 34, 21, 54, 68, 98, 23, 65] <class 'list'>


In [41]:
import numpy as np #importing numpy library
np_simple_list = np.array(simple_list)
print(np_simple_list, type(np_simple_list))

[12 34 21 54 68 98 23 65] <class 'numpy.ndarray'>


In [42]:
simple_listof_list = [[12,34,45],[35,76,87],[11,33,55,]]
print(simple_listof_list)


[[12, 34, 45], [35, 76, 87], [11, 33, 55]]


In [43]:
print(np.array(simple_listof_list),type(simple_listof_list)) #simple numpy list of 

[[12 34 45]
 [35 76 87]
 [11 33 55]] <class 'list'>


-  printing Rows and Column

In [44]:
row_vector = np.array([1,2,3])
print(row_vector,type(row_vector))

[1 2 3] <class 'numpy.ndarray'>


In [45]:
column_vector = np.array([[1],[2],[3]])
print(column_vector,type(column_vector))

[[1]
 [2]
 [3]] <class 'numpy.ndarray'>


#### Generating random array using builtin features


In [46]:
array1 = np.arange(20) # it gives 0 to 20 elements in an array
print(array1,type(array1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>


In [47]:
array2 = np.arange(0,20,4) # it start with 0 end with 19 and step is 4
print(type(array2),array2)

<class 'numpy.ndarray'> [ 0  4  8 12 16]


In [48]:
print(np.zeros(10)) #it gives zero as 10 times


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [49]:
print(np.zeros((4,3))) #specify rows and column

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [50]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [51]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Full
##fill values in array/matrix

In [52]:
array3 = np.full((4,4),fill_value=7)
print(array3)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


## linspace
### Gives 

In [53]:
lk = np.linspace(2.0,3.0,5) #apecify start end and jumps.
                            # stop value must be needed in this functions.
print(lk,lk.dtype)

type(lk)
lk.size
lk.shape

[2.   2.25 2.5  2.75 3.  ] float64


(5,)

In [54]:
print(np.linspace(0,32,10))

[ 0.          3.55555556  7.11111111 10.66666667 14.22222222 17.77777778
 21.33333333 24.88888889 28.44444444 32.        ]


In [55]:
my_randArr = np.arange(2,20,3,dtype=int)
# my_randArr = array1
print(my_randArr)
type(my_randArr)
print(my_randArr.size,"\n",
my_randArr.shape,"\n",
my_randArr.argmax(),"\n",
my_randArr.argmin(),"\n",
my_randArr.argsort(),)

[ 2  5  8 11 14 17]
6 
 (6,) 
 5 
 0 
 [0 1 2 3 4 5]


# Empty numpy
### like_array

In [59]:
Array_empty = np.empty(shape=(2,3),dtype=float,order="F",)
print(Array_empty)
Sarr_1 = array2
print(Sarr_1)
np.empty_like(Sarr_1,dtype=float,order="C",subok=True)

[ 0  4  8 12 16]


array([2.0e-323, 1.5e-323, 9.9e-324, 4.9e-324, 2.5e-323])

# Eye 
return 2d array

In [69]:
G_array0 = np.eye(3,3,dtype=int)     # Gives the diagonal identity element.
G_array1 = np.eye(3,3,dtype=int, k = 1)     # Gives the diagonal identity element.
G_array2 = np.eye(3,3,dtype=int,k=-1)     # Gives the diagonal identity element.
print(G_array0," Array 1\n",G_array1,"array2\n",G_array2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]  Array 1
 [[0 1 0]
 [0 0 1]
 [0 0 0]] array2
 [[0 0 0]
 [1 0 0]
 [0 1 0]]


## Random array


In [75]:
Rnd_array = np.random.random(5)
print(Rnd_array)
print("******************************************")
Rnd_narray = np.random.random((3,3))
print(Rnd_narray)

[0.14862148 0.61346842 0.82720976 0.16159609 0.94437163]
******************************************
[[0.46387195 0.03636395 0.40696191]
 [0.43241719 0.14062139 0.19011055]
 [0.47491115 0.42122915 0.08856959]]


In [79]:
restr_arr= np.random.randint(4,size=5)      #It returns size of integers is 5 and value is in between less than 4.
print(restr_arr)
restriced_arr = np.random.randint(1,4,size=10) # it returns integers betwwen 1 and less than 4.
print(restriced_arr)
print("\n")
Matrix_Rest_array = np.random.randint(1,6,size=(5,5))
print(Matrix_Rest_array)

[1 1 0 2 3]
[3 3 1 1 3 3 1 1 1 2]


[[2 3 3 3 1]
 [2 5 4 5 1]
 [2 3 1 3 1]
 [4 3 1 4 3]
 [3 4 5 4 2]]


# Attributes of ndarray
### shape,ravel,size,max,min.....

In [88]:
randArray = np.arange(10)   # Define some dummy array.
print(randArray)
print("\n")
sample_array = np.array([[3,6,8,9],[5,4,2,7]])
sample_array2 = np.array([3,6,8,9])
print(sample_array)
print("\n")
print(sample_array2)

[0 1 2 3 4 5 6 7 8 9]


[[3 6 8 9]
 [5 4 2 7]]


[3 6 8 9]


In [97]:
print(sample_array.shape)

print(sample_array.size)
print(sample_array.ndim) # Printing axis
print(sample_array2.ndim)

(2, 4)
8
2
1


### Method of reshaping

In [111]:
print(sample_array.reshape(4,2)) #re-shaping the size.
sample_array = sample_array.reshape((4,2))
print("\n")
print(sample_array2.reshape(2,2))
sample_array2.reshape((2,2))
# Tranpose an array

[[3 6]
 [8 9]
 [5 4]
 [2 7]]


[[3 6]
 [8 9]]
[3 6 8 9]


In [110]:
# To flatten the array from n dimension into 1 dimension.
print(sample_array.ravel())
print("\n")


[3 6 8 9 5 4 2 7]


[3 6 8 9]


In [113]:
Rsadom = np.arange(0,8,2)
print(Rsadom)
print(rand_array.argmax()) 
 # if multidimensional array, parameter axis can be provided to check max on specific axis

[0 2 4 6]
