### Operations on np
#### Airthmatic operations on NP

In [1]:
import numpy as np
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Basic airthmatic operation on numpy.
print(arr+arr) ## addition of two array, it's not concatination.
print("\n")
print(arr*arr) # multiplication of two array
print("\n")
print(arr**3) # element raise to power 3.
print("\n")
print(arr-arr)
print("\n") # Warning on division by zero, but not an error!
print(arr/arr) #replacing infinity with nan(not a number.)
print("\n")
print(1/arr)    # Also warning, but not an error instead infinity




In [9]:
# Boolean expression
print(arr>4) # Returns true and false data.

[False False False False False  True  True  True  True  True]


In [12]:
# Matrix operation
a = np.array([[1, 1],
              [0, 1]])
b = np.array([[2, 0],
              [3, 4]])
#element wise products
print(a*b)
# mAtrix product "@"
print(a@b)
#

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


### Universal Function array.
-   GIVES function of sin, cos, etc.
-   there is universal function (ufunc).
-   within numpy we do operation on every element in matrix.


In [14]:
print(np.sqrt(arr))     # Taking square root of every element.
print("\n")
print(np.exp(arr))      #Calculating exponential
print("\n")


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [16]:
new_arr = np.random.randint(10, 20, 10)  # start,   END,    No. of elements
print(new_arr)
print(np.add(new_arr, arr))  # addition perform elementwise.


[19 17 16 13 12 15 13 10 16 17]
[19 18 18 16 16 20 19 17 24 26]


In [22]:
arr = np.random.randint(2,10,10)
print(np.sin(arr)) #return radian.
print("\n")
print(np.log(arr))

[-0.7568025   0.98935825  0.90929743 -0.7568025  -0.95892427  0.41211849
  0.90929743  0.14112001 -0.95892427 -0.95892427]


[1.38629436 2.07944154 0.69314718 1.38629436 1.60943791 2.19722458
 0.69314718 1.09861229 1.60943791 1.60943791]
