### Numpy index and selection

In [6]:
import numpy as np
# Creating sample array
samp_array = np.arange(1,11) #Start,stop , step(Not np. of element{randint})
print(samp_array)

[ 1  2  3  4  5  6  7  8  9 10]


## Slicing/Indexing

In [11]:
print(samp_array[3])    # Get value at index.
print("\n")
print(samp_array[3:8]) #slicing or iterating in given range. last index is excluded.
print("\n")
print(samp_array[:5]) # getting value upto range.
print("\n")
print(samp_array[2:9:2]) # Start,stop,step.



4


[4 5 6 7 8]


[1 2 3 4 5]


[3 5 7 9]


In [13]:
samp_array[3:9] = 999 #setting values 99
print(samp_array)

[  1   2   3 999 999 999 999 999 999  10]


In [14]:
# Multidimensional array
M_arr = np.arange(15).reshape((5,3))
print(M_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [21]:
print(M_arr[4,2]) # acessing element(Note-index start from 0)
print("\n")
print(M_arr[2:4,2]) # row range,Column.
print("\n")
print(M_arr[2:4]) # printing all column


14


[ 8 11]


[[ 6  7  8]
 [ 9 10 11]]


# Boolean Indexing


In [23]:
#Creating sample array.
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
mod = [True,False,False,True,True,False,True,True,False,True]
print(array1[mod]) #Printing only true values.


[0 3 4 6 7 9]


In [29]:
# PRINT boolean values above limit.

limit = 5
above_limit = array1>limit
print(above_limit)
print("\n")
#printing all values above limits
print(array1[above_limit])

[False False False False False False  True  True  True  True]


[6 7 8 9]


In [31]:
# Indexing with boolean array.
test_arr = np.arange(12).reshape(3,4)
print(test_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
b1 = np.array([False,True,True])
print(test_arr[b1]) #print element of row which is true in b1.

[[ 4  5  6  7]
 [ 8  9 10 11]]


# COpy
-Shallow copy, deep copy, No copy

In [39]:
arr_1 = np.arange(11) # Creating a array.
# No copy
new_arr = arr_1
print(new_arr)
print(new_arr is arr_1) # checking both are same?


[ 0  1  2  3  4  5  6  7  8  9 10]
True


In [40]:
# modifing content of new array
new_arr[2] = 999
print(new_arr)

[  0   1 999   3   4   5   6   7   8   9  10]


-   Conclusion of No copy array is

###### Both the array is pointing to same address of memory adrress



In [42]:
#Checking previous arr_1
print(arr_1) # Changes are reflected in previous array.


[  0   1 999   3   4   5   6   7   8   9  10]


###### NOTE - content of array is also has been changed.


# Deep Copy

In [44]:
arr_2 = np.arange(10) # creating a new array.
print(arr_2)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
new_arr2 = arr_2.copy()
print(arr_2 is new_arr2)

False


In [50]:
# Modifying new array
new_arr2[3] = 999
print(new_arr2)

[  0   1   2 999   4   5   6   7   8   9]


In [51]:
print(arr_2)

[0 1 2 3 4 5 6 7 8 9]


###### In above statements Notes - there is no change in original array.