In [1]:
import cv2
import numpy as np
import time

In [2]:
cv2.__file__

'C:\\Users\\heman\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\cv2\\__init__.py'

### Initiating classifiers

In [8]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

## Reading image

In [5]:
img = cv2.imread('faces.jpeg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("img",img)
cv2.imshow("gray",gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Detecting face

In [9]:
faces = face_cascade.detectMultiScale(gray,scaleFactor=1.3,minNeighbors=5)
print(faces)

[[234  25  85  85]
 [363  34  86  86]]


## Enclosing face with rectangles

In [10]:
x,y,w,h = faces[0]
img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)
cv2.imshow('mg',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Creating ROI of face

In [11]:
roi_gray = gray[y:y+h,x:x+w]
roi_color = img[y:y+h,x:x+w]
cv2.imshow("roi grey face",roi_gray)
cv2.imshow("roi color",roi_color)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Detecting eye and enclosing them with rectangle

In [13]:
eyes = eye_cascade.detectMultiScale(roi_gray)
print(eyes)

[[16 18 25 25]
 [41 22 24 24]]


In [14]:
for(ex,ey,ew,eh) in eyes:
    cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,255),2)
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Multiple faces in one images

In [15]:
img = cv2.imread('faces.jpeg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)



In [20]:
faces = face_cascade.detectMultiScale(gray,1.3,5)
for(x,y,w,h) in faces:
    img = cv2.rectangle(img,(x,y),(x+w, y+h),(0,255,255),2)
    roi_gray = gray[y:y+h,x:x+w]
    roi_color = img[y:y+h,x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for(ex,ey,ew,eh)in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
print('Number of faces',len(faces))
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of faces 2
