# Data frames

In [181]:
import pandas as pd
import numpy as np

In [182]:
num_data = np.arange(25).reshape(5,5)
print(num_data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


###### creating data frames

In [183]:
frame = pd.DataFrame(data=num_data,index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4','C5'])
print(frame)
# Creating a frame using data frame pandas
#giving row name and column name.


    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24


In [184]:
frame1 = pd.DataFrame(num_data,['R1','R2','R3','R4','R5'],['C1','C2','C3','C4','C5'])
#same without keyword index,column,data
print(frame1)
print(type(frame1))

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24
<class 'pandas.core.frame.DataFrame'>


In [185]:
# Fetching complete column from column c3
print(frame['C3'])

R1     2
R2     7
R3    12
R4    17
R5    22
Name: C3, dtype: int32


In [186]:
print(frame[["C3","C4"]]) #print more than two column
# print(frame["C3","C4"]) #print more than two column 
# Note - must use double square brackets to fetch multiple columns
print(frame[["C3","C4",'C2']])

    C3  C4
R1   2   3
R2   7   8
R3  12  13
R4  17  18
R5  22  23
    C3  C4  C2
R1   2   3   1
R2   7   8   6
R3  12  13  11
R4  17  18  16
R5  22  23  21


In [187]:
print(frame.iloc[:,[0,1]]) # iloc( index lock). it fetch through indexing.
#sytanx - iloc[start of rows:,[index of row number.]]
#accessing the element by number indexing

    C1  C2
R1   0   1
R2   5   6
R3  10  11
R4  15  16
R5  20  21


###### Row indexing

In [188]:
print(frame.loc["R1"]) # accessing Rows by its index name.

C1    0
C2    1
C3    2
C4    3
C5    4
Name: R1, dtype: int32


In [189]:
print(frame.loc[["R1", "R2"]])
# accessing multiple rows

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9


In [190]:
print(frame.iloc[0]) # row can accessing by index numbers.

C1    0
C2    1
C3    2
C4    3
C5    4
Name: R1, dtype: int32


In [191]:
print(frame.loc[['R1','R2']]) # accessing multiple row.


    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9


#### Row and column indexing

In [192]:
print(frame.loc['R2', 'C3'])  # single row and single column indexing.


7


In [193]:
print(frame.loc[['R1','R3'],['C1','C4']]) # multiple row cloumn indexing.

    C1  C4
R1   0   3
R3  10  13


###### Creating a new columns

In [194]:
frame['C6'] = [100,200,300,400,500]
print(frame)

    C1  C2  C3  C4  C5   C6
R1   0   1   2   3   4  100
R2   5   6   7   8   9  200
R3  10  11  12  13  14  300
R4  15  16  17  18  19  400
R5  20  21  22  23  24  500


In [195]:
# deleting columns
## Temprory drop
frame.drop(['C6'],axis=1)

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24

In [196]:
print(frame) # Do not reflected in frame.

    C1  C2  C3  C4  C5   C6
R1   0   1   2   3   4  100
R2   5   6   7   8   9  200
R3  10  11  12  13  14  300
R4  15  16  17  18  19  400
R5  20  21  22  23  24  500


In [197]:
# Permanent drop using inplace parameter as true.
frame.drop(['C6'],axis=1,inplace=True)


In [198]:
print(frame) # Now reflected in frame.

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24


In [199]:
frame.loc["R6"] = [99,99,99,99,99] # Creating a new rows
print(frame)

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24
R6  99  99  99  99  99


In [200]:
# Deleting a row
frame.drop(["R6"]) # Temp delete - no need to give axis parameters.
#

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24

In [201]:
print(frame)  # Not reflected in original frame

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24
R6  99  99  99  99  99


In [202]:
# For permanent delete
frame.drop(["R6"],inplace=True) # deletion reflected in originial frame.

print(frame)


    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24


##### Condotional indexing

In [203]:
print([frame>10]) # It returns a boolean values corrosponding to it's index.

[       C1     C2     C3     C4     C5
R1  False  False  False  False  False
R2  False  False  False  False  False
R3  False   True   True   True   True
R4   True   True   True   True   True
R5   True   True   True   True   True]


In [204]:
# Printing all the element of frame which is greater than 10
print(frame[frame>10])

      C1    C2    C3    C4    C5
R1   NaN   NaN   NaN   NaN   NaN
R2   NaN   NaN   NaN   NaN   NaN
R3   NaN  11.0  12.0  13.0  14.0
R4  15.0  16.0  17.0  18.0  19.0
R5  20.0  21.0  22.0  23.0  24.0


In [205]:
#printing boolean for column C2 which is greater than 6.
print([frame["C2"]>6])


[R1    False
R2    False
R3     True
R4     True
R5     True
Name: C2, dtype: bool]


In [206]:
#printing all elements of all column which is greater than 6.
print(frame[frame['C2']>6])

    C1  C2  C3  C4  C5
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24


In [207]:
#printing all rows of c2 which is greater than 6.
print(frame[frame['C2']>6]['C2'])

R3    11
R4    16
R5    21
Name: C2, dtype: int64


In [208]:
print(frame[(frame['C2'] > 6) & (frame["C3"] > 12)])

#printing the element which is c2 greater than 6 and c3 is greater than 12.

    C1  C2  C3  C4  C5
R4  15  16  17  18  19
R5  20  21  22  23  24


#### Index manipulation.

In [209]:
print(frame)
# temprory reset, for permanent reset use axis parameter and inplace parameter as true
print(frame.reset_index())
# print(frame.reset_index(inplace=True))


    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24
  index  C1  C2  C3  C4  C5
0    R1   0   1   2   3   4
1    R2   5   6   7   8   9
2    R3  10  11  12  13  14
3    R4  15  16  17  18  19
4    R5  20  21  22  23  24


In [210]:
frame["new"] = ['R11','R22','R33','R44','R55']
print(frame)

    C1  C2  C3  C4  C5  new
R1   0   1   2   3   4  R11
R2   5   6   7   8   9  R22
R3  10  11  12  13  14  R33
R4  15  16  17  18  19  R44
R5  20  21  22  23  24  R55


In [211]:
frame.set_index("new") # temprory change.

C1  C2  C3  C4  C5
new                    
R11   0   1   2   3   4
R22   5   6   7   8   9
R33  10  11  12  13  14
R44  15  16  17  18  19
R55  20  21  22  23  24

In [212]:
print(frame) #change not reflected yet.

    C1  C2  C3  C4  C5  new
R1   0   1   2   3   4  R11
R2   5   6   7   8   9  R22
R3  10  11  12  13  14  R33
R4  15  16  17  18  19  R44
R5  20  21  22  23  24  R55


In [213]:
frame.set_index("new",inplace=True)
print(frame) #permanent set index/\.

     C1  C2  C3  C4  C5
new                    
R11   0   1   2   3   4
R22   5   6   7   8   9
R33  10  11  12  13  14
R44  15  16  17  18  19
R55  20  21  22  23  24


In [214]:
print(frame.axes) # print axes

[Index(['R11', 'R22', 'R33', 'R44', 'R55'], dtype='object', name='new'), Index(['C1', 'C2', 'C3', 'C4', 'C5'], dtype='object')]


In [215]:
frame.rename_axis("Column",axis=1,inplace=True)
frame.rename_axis("Row",axis=0,inplace=True)
# Permanently changes the name of axes.

In [216]:
print(frame)

Column  C1  C2  C3  C4  C5
Row                       
R11      0   1   2   3   4
R22      5   6   7   8   9
R33     10  11  12  13  14
R44     15  16  17  18  19
R55     20  21  22  23  24


In [217]:
frame.columns = ['a','b','c','d','e']
print(frame)

      a   b   c   d   e
Row                    
R11   0   1   2   3   4
R22   5   6   7   8   9
R33  10  11  12  13  14
R44  15  16  17  18  19
R55  20  21  22  23  24
