<a href='https://www.hexnbit.com/'> <img src='https://www.hexnbit.com/wp-content/uploads/2019/09/hexnbit_final_66px.png'/> </a>

Documentation: https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_drawing_functions/py_drawing_functions.html

# Drawing Functions

### Importing Packages

In [1]:
import numpy as np
import cv2

### Blank White Frame 

In [2]:
img=np.ones((511,511,3))   # np.ones will create white frame
print(img)                
cv2.imshow('frame',img)    # displaying frame
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 ...

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### Creating Black Lines

In [6]:
#                 (coordinates), (B,G,R),Thickness    Each color can hold values between 0 and 255
img=cv2.line(img,(0,0),(511,511),(0,0,0),5)          
img=cv2.line(img,(511,0),(0,511),(0,0,0),5)
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Blank Black Frame

In [7]:
img=np.zeros((511,511,3)) # np.zeros will create black frame
print(img)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### Creating Red Lines

In [8]:
#                 (coordinates), (B,G,R),Thickness
img=cv2.line(img,(0,0),(511,511),(0,0,255),5)       
img=cv2.line(img,(511,0),(0,511),(0,0,255),5)
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Creating Rectangle

In [ ]:
img_path="C:\\Users\\Rushil Soni\\Hex_N_Bit_AI&ML\\Week 4\\sample_images\\messi5.jpg"   # path for messi's image
img=cv2.imread(img_path,1)
img=cv2.rectangle(img,(150,50),(350,256),(0,0,255),2)   # creating rectangle using 2 points
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Creating Cicle

In [ ]:
img = np.zeros((512,512,3))
img_path="C:\\Users\\Rushil Soni\\Hex_N_Bit_AI&ML\\Week 4\\sample_images\\messi5.jpg"
img=cv2.imread(img_path,1)
#                  (center),Radius,(B,G,R)
img=cv2.circle(img,(245,100),50,(0,255,255),3)         
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Creating Polygon

In [ ]:
img=np.zeros([512,512,3])
pts = np.array([[200,200],[200,100],[400,100],[400,200],[300,250]], np.int32)
img = cv2.polylines(img,[pts],True,(0,255,255))   # True parameter closes the polygon, False will leave it opened
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Inserting Text

In [ ]:
img_path="C:\\Users\\Rushil Soni\\Hex_N_Bit_AI&ML\\Week 4\\sample_images\\apple.jpg"
img=cv2.imread(img_path,1)
font = cv2.FONT_HERSHEY_SIMPLEX     # font type
#               string, coordinates,font,scale,(B,G,R),Line Thickness, Line Type
cv2.putText(img,'Apple',(170,300), font, 2,(255,255,0),3,cv2.LINE_AA)
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()